language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.2
      elixir: 1.3.2
    - otp_release: 18.3
      elixir: 1.4.0
    - otp_release: 19.2
      elixir: 1.4.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
